name: RDP Port Forwarding via SSH

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (modify as needed)

jobs:
  setup-rdp-port-forwarding:
    runs-on: windows-latest  # Or your self-hosted Windows runner
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install OpenSSH Client
      run: |
        # Install OpenSSH client if it is not already installed (typically comes pre-installed)
        Add-WindowsFeature -Name OpenSSH-Client  # Install OpenSSH client if needed on Windows runner
        Start-Service ssh-agent  # Start ssh-agent service
        Set-Service -Name ssh-agent -StartupType Automatic  # Set ssh-agent to start automatically

    - name: Forward RDP Port using SSH
      run: |
        # Set variables
        $vps_user = "Administrator"  # SSH user on the VPS
        $vps_ip = "52.66.69.127"     # VPS IP address
        $vps_port = "22"             # SSH port on your VPS (adjust if different)
        $rdp_port = "4455"           # The custom RDP port on the GitHub Actions runner
        $password = "Admin@@11"      # Your SSH password

        # SSH connection to forward the port (Password Authentication for SSH)
        # In GitHub Actions, this step won't work for direct password-based SSH due to non-interactive nature

        # Normally, you would use ssh keys here, but GitHub Actions doesn't support interactive password prompts
        # You will need to replace this with an approach that supports password auth or SSH key-based auth.

        Write-Host "This is where the SSH connection setup would happen if password-based SSH worked interactively."

    - name: Test the RDP connection
      run: |
        # You would typically manually test the RDP connection using an RDP client, e.g., connect to localhost:4455.
        Write-Host "Test the RDP connection to port 4455"
